### ISSUE TITLE
Question about metadata

### ISSUE THREAD

**Issue by ttunguz** [prose/starter#12]
I can't seem to get metadata to work. I configured the metadata to show a title field but nothing seems to make it show in a new post, when I click the metadata button. I've copied and pasted this from the starter repo but still no cigar.

I'd appreciate any help. Thanks!

My config.yml is this:

name: "title"
description: ""
url: "url"
paginate: 10
markdown: rdiscount
permalink: :title

prose:
  media: 'images'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""

**Comment by tristen** [comment]
Could be a formatting issue? is your config file valid yaml?

**Comment by ttunguz** [comment]
Yes, thanks. I linted it and it's valid.

**Comment by tristen** [comment]
Can you post your config file formatted correctly to this issue then? On first glance the order reads correct.

**Comment by ttunguz** [comment]
thanks for the help!

```
name: "title"
description: ""
url: "url"
paginate: 10
markdown: rdiscount
permalink: :title

prose:
  media: 'images'
  metadata:
      _posts:
        - name: "title"
          field:
            element: "text"
            label: "Title"
            value: ""
            type: "text"
```

**Comment by tristen** [comment]
I believe the yaml config entries should be indented 2 spaces and not four. The space between your `metadata` -> `_posts` entry is 4 followed by 2. This should be consistent.

Also, is there any relevant error in the browsers console?

**Comment by ttunguz** [comment]
Thanks. I fixed this and the excerpt tag now works but title still fails. No errors in the console

```
prose:
  media: 'images'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "excerpt"
        field:
          element: "text"
          label: "Excerpt"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
```
