### ISSUE TITLE
Metadata for static pages

### ISSUE THREAD

**Issue by jdsimcoe** [prose/starter#29]
I have all of my static pages like `about.md` and `contact.md` in the root directory of my project. I can't seem to get the custom metadata editing to work for these entries. For files in `_posts` it works great. What am I missing?

Here is my Prose section of my `_config.yml`:

``` yaml
prose:
  rooturl: ''
  siteurl: 'http://meetcircle.co/'
  relativeLinks: 'http://meetcircle.co/links.jsonp'
  media: 'media'
  ignore:
    - public/
    - /_includes
    - /_layouts
    - /_sass
    - /blog
    - 404.html
    - .gitignore
    - _config.yml
    - atom.xml
    - links.jsonp
    - sitemap.xml
    - styles.scss
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "nav"
        field:
          element: "select"
          label: "Navigation"
          placeholder: "Choose Nav type"
          options:
            - name: "None"
              value: "none"
            - name: "Primary"
              value: "primary"
            - name: "Secondary"
              value: "secondary"
            - name: "Support"
              value: "support"
    _site:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "nav"
        field:
          element: "select"
          label: "Navigation"
          placeholder: "Choose Nav type"
          options:
            - name: "None"
              value: "none"
            - name: "Primary"
              value: "primary"
            - name: "Secondary"
              value: "secondary"
            - name: "Support"
              value: "support"
```
